### ISSUE TITLE
Cara melihat wallet hanya idr gimana gan?

### ISSUE THREAD

**Issue by caluxkonde** [Mame29/Indodax#10]

**Comment by papanara** [comment]
Buat kondisi saja mas.
contoh kita dapat saldonya dari fungsi get_info()

account = indodax(key, secret)
info = json.loads(account.get_info()) #ini utk rubah ke dictionary

saldo_aktif = info['return']['balance']
for i in saldo_aktif:
  if i == 'idr':
     print(saldo_aktif[i])

**Comment by caluxkonde** [comment]
ok makasi masih
