### ISSUE TITLE
CARA

### ISSUE THREAD

**Issue by aguspurwita** [Mame29/Indodax#2]
mau tanya bang.. cara jalankannya gimana bang??

pythhon setup.py installl
selalu error hasilnya..
terimakasih.

**Comment by Mame29** [comment]
pip install requests
pip install indodax

Pada tanggal Kam, 17 Des 2020 10.30 AM, aguspurwita <
notifications@github.com> menulis:

**Comment by aguspurwita** [comment]
yang itu sudah bang..
tapi pada saat menjalankan scriptnya error bang.
saya pakai terminal linux

**Comment by Mame29** [comment]
Error'nya dimananya ??

Pada tanggal Kam, 17 Des 2020 12.24 PM, aguspurwita <
notifications@github.com> menulis:

**Comment by aguspurwita** [comment]
python3 setup.py
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: no commands supplied

muncul seperti itu bang..
tutorial yang bener gimana ya bang?

**Comment by Mame29** [comment]
```sh
python3 setup.py sdist bdist_wheel
```
kemungkinan seperti ini untuk cmd nya

**Comment by Mame29** [comment]
> python3 setup.py
> usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
> or: setup.py --help [cmd1 cmd2 ...]
> or: setup.py --help-commands
> or: setup.py cmd --help
> 
> error: no commands supplied
> 
> muncul seperti itu bang..
> tutorial yang bener gimana ya bang?

```sh
python3 setup.py sdist bdist_wheel
```
Mungkin seperti ini maksud anda
