### ISSUE TITLE
nonce 

### ISSUE THREAD

**Issue by hikmahgumelar** [Mame29/Indodax#3]
bro gw test sell tapi ada muncul error invalid nonce

**Comment by hikmahgumelar** [comment]
{
    "success": 0,
    "error": "Nonce must be greater than 1614598870. You provided 1614598870.",
    "error_code": "invalid_nonce"
}

**Comment by Mame29** [comment]
Ada sedikit pembaruan di modulnya, saya belum sempat untuk menambahkan
ya🙏🙏

Pada tanggal Sen, 1 Mar 2021 6.41 PM, Hikmah Gumelar <
notifications@github.com> menulis:

**Comment by hikmahgumelar** [comment]
thanks fast responnya bro 
ada satu lagi di trade_sell(coin , harga_rupiah, jumlah_coin) betulkan?
klo saya jalankan 
{
    "success": 0,
    "error": "Minimum price 1 IDR",
    "error_code": ""
}

**Comment by Mame29** [comment]
Iya itu benar

Pada tanggal Kam, 4 Mar 2021 1.30 AM, Hikmah Gumelar <
notifications@github.com> menulis:

**Comment by indrawanalghifary** [comment]
Nonce nya tolong di perbaiki gan

**Comment by hikmahgumelar** [comment]
Udah di PR gan tinggal di merge sama author

**Comment by Mame29** [comment]
Ok sudah selesai
