### ISSUE TITLE
 "error": "Nonce must be greater than 1617761986917. You provided 1617809191

### ISSUE THREAD

**Issue by papanara** [Mame29/Indodax#6]
Sudah sesuai petunjuk penggunaan, namun muncul pesan error ini.

**Comment by Mame29** [comment]
> Sudah sesuai petunjuk penggunaan, namun muncul pesan kesalahan ini.

Muncul kesalahan seperti apa ??

**Comment by Mame29** [comment]
> Sudah sesuai petunjuk penggunaan, namun muncul pesan error ini.

Masalah sudah saya perbaiki

**Comment by amao71** [comment]
boleh saya dapat email address atau no wa nya? saya ingin minta bantuan modif aplikasi trading dengan binance, tapi menggunakan api indodax.  wa saya: 081299898883. terima kasih sebelumnya

**Comment by papanara** [comment]
Ada kesalahan di secret sama key saya, setelah saya perbarui pake yang baru program sudah bisa berjalan.
