### ISSUE TITLE
bug di function order_history

### ISSUE THREAD

**Issue by papanara** [Mame29/Indodax#7]
Sering terjadi kesalahan ketika memanggil order_history.

Contoh :

from indodax import indodax
import json

account = indodax(key, secret)
order = indodax.order_history('btc')
data = json.loads(order)
a = data['return']['order']
print(a['price'))

Disini ketika dipanggil terkadang bisa, output yang keluar adalah data harga beli.
tapi juga sering muncul keterangan KeyError: 'return'

**Comment by papanara** [comment]
![error](https://user-images.githubusercontent.com/20887795/114646808-8a47db00-9d0e-11eb-8c69-2605a6621f79.png)

Ini contohnya.
tanpa melakukan perubahan kode, saya hanya memangilnya berulang2 kali.

**Comment by Mame29** [comment]
coba di kasih jeda

Pada tanggal Rab, 14 Apr 2021 pukul 09.46 Agan Nain <
***@***.***> menulis:

**Comment by papanara** [comment]
Maksud saya adalah dia baru merespon setelah berulang kali dipanggil.

Contoh pada panggilan pertama dia munculnya KeyError, dia baru berhasil setelah panggilan 3 atau ke 4, atau terkadang kedua

**Comment by hikmahgumelar** [comment]
coba menggunakan try and except working di saya

![image](https://user-images.githubusercontent.com/4201453/115393364-cd70e500-a20b-11eb-97b5-940db59d2daf.png)


Signal botnya menggunakan apa? klo saya RSI

**Comment by Mame29** [comment]
> coba gunakan try dan kecuali working di saya
> 
> ![gambar](https://user-images.githubusercontent.com/4201453/115393364-cd70e500-a20b-11eb-97b5-940db59d2daf.png)
> 
> Signal botnya menggunakan APA? klo saya RSI

Untung pemanggilan order_history menggunakan parameter yg sama
contoh:
```sh
>>> from indodax import indodax
>>> ab = indodax(api_key, secret_key)
>>> ab.order_history('btc')
