### ISSUE TITLE
Cara untuk instant order gimana gan?

### ISSUE THREAD

**Issue by alanrizky** [Mame29/Indodax#8]
Saya tidak melihat adanya fungsi untuk Instant Order, adanya cuman Limit Order. Apakah saya harus menambahkan parameter lagi di variable `m` di fungsi `trade_buy`? Trims gan. 
![Capture](https://user-images.githubusercontent.com/39402095/114780399-8b761800-9da1-11eb-986b-9375f35f2ea1.JPG)

**Comment by alanrizky** [comment]
```
def trade_buy(self, coin, diharga, jumlah, idr_or_btc='idr'):
    ''' lanjutan intruksi di atas
    >>> a.trade_buy('doge', '41', '50000') # kita akan membeli doge 50rb

    '''
    pair = coin+'_'+idr_or_btc
    m = {
      'pair': pair,
      'type': 'buy',
      'price': diharga,
      idr_or_btc: jumlah,
    }

    return self.query('trade', **m)
```

**Comment by papanara** [comment]
Buat kondisi saja saya pikir gan.
ambil bid/ask price yang ada di daftar order. 

While asset > 0:
  jalankan trade_buy / sell dengan harga yang ada di ask/bid.
 
jadi kayak ngeforce utk ikut harga pasar

**Comment by papanara** [comment]
ask/bid price = ini ambil data ask/bid # tergantung mau sell atau beli

jadi contoh mau jual tinggal masukan saja harga diatas tersebut ke dalam parameternya.

dan untuk memastikan bahwa semua koin atau asset terjual tinggal buat kondisi.
karna terkadang, yang ada dalam daftar order, volumenya hanya kecil.

**Comment by alanrizky** [comment]
Baik gan. Soalnya saya kira cuman nambahin 1 parameter di variable `m`.

**Comment by Mame29** [comment]
di versi 1.3 sudah tersedia instan order, mungkin perlu untuk pengujian terlebih dahulu
